export const newsData = [
  {
    id: 0,
    symbol: "BTC",
    title: "The previous day, US BTC spot ETF net inflow of 260 billion won 6 consecutive trading days",
    content: "According to Trader T, an account that tracks the flow of funds in U.S. cryptocurrency spot ETFs, a total of $189.09 million was recorded as having a net inflow into U.S. Bitcoin spot ETFs on January 23(local time). This is the sixth consecutive trading day of net inflow.",
    date: "Jan 24, 2025",
    source: "Coinness",
  },
  {
    id: 1,
    symbol: "BTC",
    title: "Former Binance CEO: US Government's BTC Strategic Asset Reserve is Almost Certain",
    content: "Former Binance CEO Changpeng Zhao announced on his X that Senator Cynthia Lummis had been appointed as the Chair of the Subcommittee on Digital Assets (Cryptocurrencies), saying, The US government's strategic asset reserve of Bitcoin is almost certain. He added, Cryptocurrencies are moving at the speed of cryptocurrencies again.",
    date: "Jan 24, 2025",
    source: "Coinness",
  },
  {
    id: 2,
    symbol: "BTC",
    title: "Deutsche Bank: 'BTC’s Rising Trend Continues This Year Cryptocurrency Golden Age'",
    content:"According to CoinDesk, Germany's largest commercial bank, Deutsche Bank, said, 'Bitcoin is expected to be bullish this year, and the price is expected to continue to rise.' It added, 'In order for the golden age of cryptocurrencies to continue, continued support from US President Donald Trump is essential. In addition, the political background, regulatory environment, institutional introduction, and the Fed's loose monetary policy in the US are expected to support the price of cryptocurrencies.'",
    date: "Jan 24, 2025",
    source: "Coinness",
  },
  {
    id: 3,
    symbol: "BTC",
    title: "Analysis 'BTC Cycle High $150K'",
    content: "According to Cointelegraph, Glassnode Senior Analyst James Check predicted that Bitcoin could follow the 2016-2017 cycle pattern and reach a high of $150,000. The averages for short-term and long-term holders are $90,349 and $24,627, respectively, which means that if Bitcoin reaches $150,000, short-term holders can make a profit of 66% and long-term holders can make a profit of 509%.",
    date: "Jan 24, 2025",
    source: "Coinness",
  },
  {
    id: 4,
    symbol: "DOGE",
    title: "Bitwise files DOGE ETF with Delaware SEC",
    content: "According to Trinews, American asset management company Bitwise has completed registration of a Dogecoin (DOGE) ETF entity in Delaware, USA. Bloomberg analyst James Seifart explained, 'This is just a trust registration, not an official ETF report.' His colleague Eric Balchunas also said, 'After checking, this is legal, contrary to rumors such as the BlackRock Ripple (XRP) ETF.'",
    date: "Jan 23, 2025",
    source: "Coinness",
  },
  {
    id: 5,
    symbol: "DOGE",
    title: "Analysis “Trump Era Begins, Possibility of Approval of Memecoin ETF↑”",
    content: "According to Cointelegraph, Dmitrij Radin, CTO of cryptocurrency regulation and infrastructure firm Fideum, said that with the arrival of a crypto-friendly Securities and Exchange Commission (SEC) led by President Donald Trump, the likelihood of memetic coin ETFs such as TRUMP, BONK, and DOGE being approved has increased.",
    date: "Jan 23, 2025",
    source: "Coinness",
  },
  {
    id: 6,
    symbol: "DOGE",
    title: "Analysis 'DOGE, expected to be strong starting next week'",
    content: "Ali Martinez, a cryptocurrency analyst and trader, told X that 'During the last bull cycle, DOGE experienced a 56% correction and started to rise on January 25, 2021. Given that DOGE has experienced a 46% correction in the past few weeks, an uptrend could begin as early as next week.'",
    date: "Jan 16, 2025",
    source: "Coinness",
  },
  {
    id: 7,
    symbol: "DOGE",
    title: "[Crypto Awards] The most popular coin of 2024 is 'Solana' Dogecoin takes 2nd place",
    content: "Solana (SOL) was selected as the K-Community Cryptocurrency of the Year at the '2024 Korea Crypto Awards' hosted by Coinness, Korea's largest cryptocurrency media and community platform. This category awards the cryptocurrency that received the most attention in the Korean crypto community in 2024. The evaluation was conducted by combining the number of mentions (60%) and search volume (40%).",
    date: "Jan 2, 2025",
    source: "Coinness",
  },
];
