/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CV } from "./CV";
export * as factories from "./factories";
export { CV__factory } from "./factories/CV__factory";
